### ISSUE TITLE
Clarify intersectionRatio vs options.threshold behavior

### ISSUE THREAD

**Issue by oyeanuj** [jscottsmith/react-observed#2]
Hi @jscottsmith,

Thank you for putting out this library - has been super helpful so far. 

The one place where I found myself confused originally is understanding the difference between `intersectionRatio` and `options.threshold`. Once I looked at the code, the intent became a little clearer but I noticed that the `options.threshold` is set `1` by default - that means that if someone only supplies the `intersectionRatio`, then it is never really used since it will always be less than or equal to the default threshold.

Should the default `options.threshold` be either 0 or equal to the passed in `intersectionRatio`?

**Comment by jscottsmith** [comment]
@oyeanuj Thanks, I still need to clarify the README, especially in regards to the props you bring up.

> Should the default `options.threshold` be either `0` or equal to the passed in `intersectionRatio`?

Ya I see your point. I suppose the `options.threshold` should be changed to `0`, since that's true default of the `IntersectionObserver` if no threshold is supplied to the constructor. I'd also make the `intersectionRatio` default to `0`. Which means the observed element will be considered in view the moment the first pixel is in view.

I'll change this and work on clarifying the README.
